FROM mongo:7.0.14

RUN apt-get update
RUN apt-get install uuid-runtime gettext-base wget postgresql-client-14 nano curl -y
RUN wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && chmod +x /usr/local/bin/yq
